# Generated by Django 5.0.1 on 2024-03-30 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('a_username', models.CharField(max_length=255)),
                ('a_name', models.CharField(max_length=255)),
                ('a_surname', models.CharField(max_length=255)),
                ('a_email', models.CharField(blank=True, max_length=255, null=True)),
                ('a_phone', models.CharField(max_length=13)),
                ('a_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id_shoes', models.AutoField(primary_key=True, serialize=False)),
                ('sh_name', models.CharField(max_length=255)),
                ('sh_model', models.CharField(max_length=255)),
                ('sh_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sh_color', models.CharField(max_length=255)),
                ('sh_manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('sh_count', models.IntegerField()),
                ('sh_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sh_image', models.BinaryField()),
            ],
            options={
                'db_table': 'shoes',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('u_username', models.CharField(max_length=255)),
                ('u_name', models.CharField(max_length=255)),
                ('u_surname', models.CharField(max_length=255)),
                ('u_email', models.CharField(blank=True, max_length=255, null=True)),
                ('u_phone', models.CharField(max_length=13)),
                ('u_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('r_start_date', models.DateTimeField(auto_now_add=True)),
                ('r_end_date', models.DateTimeField()),
                ('r_shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.shoes')),
                ('r_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.users')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('o_count', models.IntegerField()),
                ('o_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('o_status', models.CharField(choices=[('Прийнято', 'accepted'), ('Оплачено', 'paid'), ('В обробці', 'in_processing'), ('Відправлено', 'shipped'), ('Доставлено', 'delivered'), ('Оплачено поставнику', 'paid_to_dropper')], max_length=45)),
                ('o_shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.shoes')),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.users')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
