# Generated by Django 5.0.1 on 2024-04-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='id_shoes',
            field=models.AutoField(auto_created=True, default=1, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
