# Generated by Django 5.0.4 on 2024-06-21 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='o_user',
            field=models.ForeignKey(db_column='o_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservations',
            name='r_user',
            field=models.ForeignKey(db_column='r_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservations',
            name='r_shoes',
            field=models.ForeignKey(db_column='r_shoes', on_delete=django.db.models.deletion.CASCADE, to='manager_app.shoes'),
        ),
        migrations.AddField(
            model_name='orders',
            name='o_shoes',
            field=models.ForeignKey(db_column='o_shoes', on_delete=django.db.models.deletion.CASCADE, to='manager_app.shoes'),
        ),
    ]
