# Generated by Django 5.0.4 on 2024-05-22 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='o_date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
