# Generated by Django 5.0.4 on 2024-06-21 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='r_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 22, 49, 47, 790581, tzinfo=datetime.timezone.utc)),
        ),
    ]
