# Generated by Django 5.0.4 on 2024-05-22 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_orders_o_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='o_date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
