# Generated by Django 5.0.1 on 2024-04-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_alter_shoes_id_shoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='id_shoes',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
