# Generated by Django 5.0.4 on 2024-06-11 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_alter_reservations_r_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoes',
            options={},
        ),
        migrations.AlterField(
            model_name='reservations',
            name='r_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 11, 16, 5, 43, 169561, tzinfo=datetime.timezone.utc)),
        ),
    ]
