# Generated by Django 5.0.1 on 2024-04-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_alter_shoes_id_shoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='id_shoes',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='sh_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
