# Generated by Django 5.0.1 on 2024-04-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_alter_shoes_id_shoes_alter_shoes_sh_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoes',
            options={'managed': False},
        ),
    ]
