# Generated by Django 5.0.1 on 2024-04-13 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0005_alter_shoes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager_app.shoes')),
            ],
        ),
    ]
