# Generated by Django 5.0.1 on 2024-04-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0006_shoesimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(max_length=2)),
            ],
        ),
    ]
