# Generated by Django 5.0.4 on 2024-06-17 14:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0006_alter_reservations_r_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='o_user',
            field=models.ForeignKey(db_column='o_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='r_user',
            field=models.ForeignKey(db_column='r_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='r_end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 17, 41, 44, 447531, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
