# Generated by Django 5.0.4 on 2024-06-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
